CREATE TABLE IF NOT EXISTS fb_user  (name VARCHAR(20), contact_no VARCHAR(15), email VARCHAR(50), password VARCHAR(50), country VARCHAR(50), city VARCHAR(50), type_of_user INT(11) DEFAULT 0, create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id INT(11) AUTO_INCREMENT PRIMARY KEY, subdomain_name VARCHAR(100) UNIQUE);
CREATE TABLE IF NOT EXISTS form  (title VARCHAR(50), description VARCHAR(100), action VARCHAR(50), enctype VARCHAR(50), method varchar(15), target VARCHAR(20), create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50) PRIMARY KEY, form_alignment VARCHAR(50));
CREATE TABLE IF NOT EXISTS account_to_form (form_id VARCHAR(50), account_id INT(11), PRIMARY KEY (form_id, account_id), FOREIGN KEY (form_id) REFERENCES form (id), FOREIGN KEY (account_id) REFERENCES fb_user (id));
CREATE TABLE IF NOT EXISTS form_to_element (form_id VARCHAR(50), element_id VARCHAR(50), type VARCHAR(50), display_no INT(10), PRIMARY KEY (form_id, element_id));
CREATE TABLE IF NOT EXISTS label_field  (form_id VARCHAR(50), name VARCHAR(50), for_attr VARCHAR(50), value VARCHAR(200), create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50), hidden VARCHAR(10), PRIMARY KEY (form_id, id), FOREIGN KEY (form_id) REFERENCES form (id));
CREATE TABLE IF NOT EXISTS text_field  (form_id VARCHAR(50), name VARCHAR(50), label_id VARCHAR(50), maxlength VARCHAR(5), size VARCHAR(5), hidden VARCHAR(10),create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50), PRIMARY KEY (form_id, id), FOREIGN KEY (form_id, label_id) REFERENCES label_field (form_id, id));
CREATE TABLE IF NOT EXISTS number_field  (form_id VARCHAR(50), name VARCHAR(50), label_id VARCHAR(50), maxlength VARCHAR(5), size VARCHAR(5), hidden VARCHAR(10),create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50), PRIMARY KEY (form_id, id), FOREIGN KEY (form_id, label_id) REFERENCES label_field (form_id, id));
CREATE TABLE IF NOT EXISTS file_field  (form_id VARCHAR(50), name VARCHAR(50), maxlength VARCHAR(5), size VARCHAR(5), hidden VARCHAR(10),create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50), PRIMARY KEY (form_id, id), FOREIGN KEY (form_id) REFERENCES form (id));
CREATE TABLE IF NOT EXISTS submit_field  (form_id VARCHAR(50), name VARCHAR(50), value VARCHAR(50), hidden VARCHAR(10),create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50), PRIMARY KEY (form_id, id), FOREIGN KEY (form_id) REFERENCES form (id));
CREATE TABLE IF NOT EXISTS reset_field  (form_id VARCHAR(50), name VARCHAR(50), value VARCHAR(50), hidden VARCHAR(10),create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50), PRIMARY KEY (form_id, id), FOREIGN KEY (form_id) REFERENCES form (id));
CREATE TABLE IF NOT EXISTS password_field  (form_id VARCHAR(50), name VARCHAR(50), label_id VARCHAR(50), maxlength VARCHAR(5), size VARCHAR(5), hidden VARCHAR(10),create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50), disabled VARCHAR(10), readonly VARCHAR(10), PRIMARY KEY (form_id, id), FOREIGN KEY (form_id, label_id) REFERENCES label_field (form_id, id));
CREATE TABLE IF NOT EXISTS textarea_field  (form_id VARCHAR(50), name VARCHAR(50), label_id VARCHAR(50), hidden VARCHAR(10), create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50), disabled VARCHAR(10), readonly VARCHAR(10), cols VARCHAR(5), rows VARCHAR(5), PRIMARY KEY (form_id, id), FOREIGN KEY (form_id, label_id) REFERENCES label_field (form_id, id));
CREATE TABLE IF NOT EXISTS checkboxgroup_field  (form_id VARCHAR(50), name VARCHAR(50), hidden VARCHAR(10), value VARCHAR(50), create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50), label_id VARCHAR(50), PRIMARY KEY (form_id, id), FOREIGN KEY (form_id, label_id) REFERENCES label_field (form_id, id));
CREATE TABLE IF NOT EXISTS radioboxgroup_field  (form_id VARCHAR(50), name VARCHAR(50), hidden VARCHAR(10), value VARCHAR(50), create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50), label_id VARCHAR(50), PRIMARY KEY (form_id, id), FOREIGN KEY (form_id, label_id) REFERENCES label_field (form_id, id));
CREATE TABLE IF NOT EXISTS radio_field  (form_id VARCHAR(50), name VARCHAR(50), label_id VARCHAR(50), hidden VARCHAR(10), value VARCHAR(50), create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50), disabled VARCHAR(10), readonly VARCHAR(10), checked VARCHAR(10), group_id VARCHAR(50), PRIMARY KEY (form_id, group_id, id), FOREIGN KEY (form_id, label_id) REFERENCES label_field (form_id, id), FOREIGN KEY (form_id, group_id) REFERENCES radioboxgroup_field (form_id, id));
CREATE TABLE IF NOT EXISTS checkbox_field  (form_id VARCHAR(50), name VARCHAR(50), label_id VARCHAR(50), hidden VARCHAR(10), value VARCHAR(50), create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50), disabled VARCHAR(10), readonly VARCHAR(10), checked VARCHAR(10), group_id VARCHAR(50), PRIMARY KEY (form_id, id), FOREIGN KEY (form_id, label_id) REFERENCES label_field (form_id, id), FOREIGN KEY (form_id, group_id) REFERENCES checkboxgroup_field (form_id, id));
CREATE TABLE IF NOT EXISTS checkboxgroup_to_checkbox (form_id VARCHAR(50), group_id VARCHAR(50), element_id VARCHAR(50), display_no INT(5), PRIMARY KEY (form_id, group_id, element_id));
CREATE TABLE IF NOT EXISTS radioboxgroup_to_radiobox (form_id VARCHAR(50), group_id VARCHAR(50), element_id VARCHAR(50), display_no INT(5), PRIMARY KEY (form_id, group_id, element_id));
CREATE TABLE IF NOT EXISTS select_field  (form_id VARCHAR(50), name VARCHAR(50), hidden VARCHAR(10), value VARCHAR(50), create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50), multiple VARCHAR(10),label_id VARCHAR(50), PRIMARY KEY (form_id, id), FOREIGN KEY (form_id, label_id) REFERENCES label_field (form_id, id));
CREATE TABLE IF NOT EXISTS option_field  (form_id VARCHAR(50), name VARCHAR(50), hidden VARCHAR(10), value VARCHAR(50), create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, id VARCHAR(50), select_id VARCHAR(50), disabled VARCHAR(10), selected VARCHAR(10), PRIMARY KEY (form_id, select_id, id), FOREIGN KEY (form_id, select_id) REFERENCES select_field (form_id, id));
CREATE TABLE IF NOT EXISTS select_to_element (form_id VARCHAR(50), select_id VARCHAR(50), type VARCHAR(50), element_id VARCHAR(50), display_no INT(5), PRIMARY KEY (form_id, select_id, element_id));


CREATE TABLE IF NOT EXISTS checkbox_field_data (form_id VARCHAR(50), group_id varchar(50), id VARCHAR(50), create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, field_id VARCHAR(50), value VARCHAR(50), PRIMARY KEY(form_id, group_id, id, field_id), FOREIGN KEY (form_id, group_id, id, field_id) REFERENCES checkboxgroup_field_data (form_id, group_id, id, element_id));

